# AI Incidents Pipeline Runner

Loads the configuration from `config/params.yaml` and runs the full pipeline:
ingestion -> preprocessing -> NLP -> sentiment -> analysis -> visualization/report.

In [1]:
from pathlib import Path

import yaml

from src import configure_logging, set_global_seeds
from src.ingestion import load_and_validate
from src.preprocessing import preprocess
from src.nlp import process_text
from src.sentiment import run_sentiment
from src.analysis import run_analysis
from src.visualization import run_visualization

In [2]:
with open("config/params.yaml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

configure_logging()
set_global_seeds(config["random_state"])

In [3]:
df = load_and_validate(config)
df.head()

2026-08-06 23:33:33,546 [INFO] src.ingestion: Loaded 1605 rows from data\raw\aiid_incidents.csv (encoding=utf-8)
2026-08-06 23:33:33,550 [INFO] src.ingestion: Column 'geo_zone' has 87.5% null values
2026-08-06 23:33:33,552 [INFO] src.ingestion: Column 'tags_list' has 6.8% null values
2026-08-06 23:33:33,573 [INFO] src.ingestion: No duplicate rows found

,Incident ID,event_date,year,title,text_data,deployer,developer,harmed,Editors,Implicated Systems,...,Detrimental Content,Impact on Critical Services,Multiple AI Interaction,Embedded,Entities,Physical Objects,Deployed,Estimated Date,Estimated Harm Quantities,Special Interest Intangible Harm
0,1,2015-05-19 00:00:00,2015,Google’s YouTube Kids App Presents Inappropria...,YouTube’s content filtering and recommendation...,Youtube,Youtube,Minors,619B47Ea5Eed5334Edfa3Bbc,NaN,...,yes,no,no,no,"[{""attributes"": [{""short_name"": ""Entity"", ""val...",no,yes,True,False,yes
1,2,2018-12-05 00:00:00,2018,Warehouse robot ruptures can of bear spray and...,Twenty-four Amazon workers in New Jersey were ...,Amazon,Amazon,Warehouse Workers,619B47Ea5Eed5334Edfa3Bbc,NaN,...,no,no,no,yes,"[{""attributes"": [{""short_name"": ""Entity"", ""val...",yes,yes,False,False,no
2,3,2018-10-27 00:00:00,2018,Crashes with Maneuvering Characteristics Augme...,"A Boeing 737 crashed into the sea, killing 189...",Boeing,Boeing,"Airplane Passengers, Airplane Crew",619B47Ea5Eed5334Edfa3Bbc,NaN,...,no,no,no,yes,"[{""attributes"": [{""short_name"": ""Entity"", ""val...",yes,yes,False,False,no
3,4,2018-03-18 00:00:00,2018,Uber AV Killed Pedestrian in Arizona,An Uber autonomous vehicle (AV) in autonomous ...,Uber,Uber,"Elaine Herzberg, Pedestrians","619B47Ea5Eed5334Edfa3Bbc, 62970Eca16E5E43939C2...",NaN,...,no,no,no,yes,"[{""attributes"": [{""short_name"": ""Entity"", ""val...",yes,no,False,False,no
4,5,2015-07-13 00:00:00,2015,Collection of Robotic Surgery Malfunctions,Study on database reports of robotic surgery m...,"Hospitals, Doctors",Intuitive Surgical,Patients,619B47Ea5Eed5334Edfa3Bbc,NaN,...,no,no,no,yes,"[{""attributes"": [{""short_name"": ""Entity"", ""val...",yes,yes,True,False,no

In [4]:
df = preprocess(df, config)
df.head()

2026-08-06 23:33:33,664 [INFO] src.preprocessing: Dropping 939 rows outside year range [2014, 2023]
2026-08-06 23:33:33,670 [INFO] src.preprocessing: Dropping 544 rows outside regions ['North America', 'Europe', 'Asia']

,Incident ID,event_date,year,title,text_data,deployer,developer,harmed,Editors,Implicated Systems,...,mlb_industries__law enforcement,mlb_industries__manufacturing,mlb_industries__other,mlb_industries__other service activities,"mlb_industries__professional, scientific and technical activities",mlb_industries__public administration,mlb_industries__real estate activities,mlb_industries__transportation and storage,mlb_industries__unclear,mlb_industries__wholesale and retail trade
0,1,2015-05-19,2015,Google’s YouTube Kids App Presents Inappropria...,YouTube’s content filtering and recommendation...,Youtube,Youtube,Minors,619B47Ea5Eed5334Edfa3Bbc,NaN,...,0,0,0,0,0,0,0,0,0,0
1,2,2018-12-05,2018,Warehouse robot ruptures can of bear spray and...,Twenty-four Amazon workers in New Jersey were ...,Amazon,Amazon,Warehouse Workers,619B47Ea5Eed5334Edfa3Bbc,NaN,...,0,0,0,0,0,0,0,0,0,1
2,3,2018-10-27,2018,Crashes with Maneuvering Characteristics Augme...,"A Boeing 737 crashed into the sea, killing 189...",Boeing,Boeing,"Airplane Passengers, Airplane Crew",619B47Ea5Eed5334Edfa3Bbc,NaN,...,0,0,0,0,0,0,0,1,0,0
3,4,2018-03-18,2018,Uber AV Killed Pedestrian in Arizona,An Uber autonomous vehicle (AV) in autonomous ...,Uber,Uber,"Elaine Herzberg, Pedestrians","619B47Ea5Eed5334Edfa3Bbc, 62970Eca16E5E43939C2...",NaN,...,0,0,0,0,0,0,0,1,0,0
4,5,2015-07-13,2015,Collection of Robotic Surgery Malfunctions,Study on database reports of robotic surgery m...,"Hospitals, Doctors",Intuitive Surgical,Patients,619B47Ea5Eed5334Edfa3Bbc,NaN,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df = process_text(df, config)
df[["tokens", "mental_health_flag"]].head()

2026-08-06 23:33:33,724 [INFO] src.nlp: Downloading NLTK resource 'wordnet'
2026-08-06 23:33:34,023 [INFO] src.nlp: Downloading NLTK resource 'omw-1.4'

                                              tokens  mental_health_flag
0  [youtubes, content, filtering, recommendation,...                   0
1  [twentyfour, amazon, worker, jersey, hospitali...                   0
2  [boeing, 737, crashed, sea, killing, 189, peop...                   0
3  [uber, autonomous, vehicle, autonomous, mode, ...                   0
4  [study, database, robotic, surgery, malfunctio...                   0

In [6]:
df = run_sentiment(df, config)
df[["sentiment_score", "sentiment_label"]].head()

2026-08-06 23:33:42,693 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:44,448 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:45,580 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:46,517 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:47,193 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:48,161 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:49,087 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:49,762 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:50,780 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:52,478 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:53,482 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:54,398 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:55,231 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:56,288 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:57,037 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:57,722 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:58,597 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:33:59,416 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:00,263 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:01,009 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:01,774 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:02,481 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:03,146 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:04,630 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:05,261 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:06,145 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:06,938 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:08,668 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:09,381 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:10,087 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:11,064 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:11,758 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:12,679 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:13,476 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:14,300 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:15,058 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:15,679 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:16,624 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:17,536 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:18,195 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:18,815 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:19,378 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:20,181 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:20,922 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:21,529 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:22,309 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:23,312 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:24,145 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:25,164 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:25,834 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:26,477 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:27,085 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:27,657 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:28,273 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:29,095 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:29,822 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:30,472 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:31,438 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:32,154 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:32,787 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:33,386 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:34,052 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:34,768 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:35,475 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:36,139 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:37,049 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:37,749 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:38,764 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:39,664 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:40,246 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:40,998 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:43,266 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:43,926 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:44,692 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:45,308 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:45,992 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:46,807 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:47,457 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:48,198 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:49,195 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:49,847 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:50,802 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:51,472 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:52,239 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:52,877 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:53,856 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:54,505 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:55,954 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:56,797 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:57,702 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:58,418 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:59,033 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:34:59,727 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:00,417 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:01,280 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:01,944 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:02,694 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:03,507 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:04,427 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:05,114 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:06,115 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:06,758 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:07,482 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:08,097 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:08,776 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:09,507 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:10,218 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:10,867 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:11,915 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:12,648 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:13,578 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:14,393 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:15,165 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:15,925 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:16,518 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:17,173 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:17,940 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:18,644 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:19,382 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:20,041 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:21,020 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-08-06 23:35:21,817 [INFO] httpx: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

   sentiment_score sentiment_label
0              0.8            Alta
1              0.7            Alta
2              1.0            Alta
3              0.9            Alta
4              0.7            Alta

In [7]:
processed_path = Path(config["data"]["processed_path"])
processed_path.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(processed_path)

In [8]:
metrics = run_analysis(df, config)

2026-08-06 23:35:22,238 [INFO] src.analysis: Metrics written to outputs\reports\metrics.json

In [9]:
report_path = run_visualization(df, metrics, config)
report_path

2026-08-06 23:35:22,855 [INFO] src.visualization: Saved figure 'regional_evolution' to outputs\figures\regional_evolution.png
2026-08-06 23:35:23,122 [INFO] src.visualization: Saved figure 'cumulative_concentration' to outputs\figures\cumulative_concentration.png
2026-08-06 23:35:23,559 [INFO] src.visualization: Saved figure 'principles_distribution' to outputs\figures\principles_distribution.png
2026-08-06 23:35:24,108 [INFO] src.visualization: Saved figure 'harm_types_distribution' to outputs\figures\harm_types_distribution.png
2026-08-06 23:35:24,515 [INFO] src.visualization: Saved figure 'stakeholders_distribution' to outputs\figures\stakeholders_distribution.png
2026-08-06 23:35:24,772 [INFO] src.visualization: Saved figure 'vulnerable_groups' to outputs\figures\vulnerable_groups.png
2026-08-06 23:35:25,208 [INFO] src.visualization: Saved figure 'harm_chronology' to outputs\figures\harm_chronology.png
2026-08-06 23:35:25,794 [INFO] src.visualization: Saved figure 'top_industries' to outputs\figures\top_industries.png
2026-08-06 23:35:25,804 [INFO] matplotlib.category: Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2026-08-06 23:35:25,806 [INFO] matplotlib.category: Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2026-08-06 23:35:26,101 [INFO] src.visualization: Saved figure 'harm_severity_index' to outputs\figures\harm_severity_index.png
2026-08-06 23:35:26,128 [INFO] matplotlib.category: Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2026-08-06 23:35:26,128 [INFO] matplotlib.category: Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2026-08-06 23:35:26,158 [INFO] matplotlib.category: Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2026-08-06 23:35:26,158 [INFO] matplotlib.category: Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2026-08-06 23:35:26,648 [INFO] src.visualization: Saved figure 'mental_health' to outputs\figures\mental_health.png
2026-08-06 23:35:29,267 [INFO] src.visualization: Saved figure 'negativity_by_principle' to outputs\figures\negativity_by_principle.png
2026-08-06 23:35:32,268 [INFO] src.visualization: Saved figure 'wordcloud_general' to outputs\figures\wordcloud_general.png
2026-08-06 23:35:34,600 [INFO] src.visualization: Saved figure 'wordcloud_north_america' to outputs\figures\wordcloud_north_america.png
2026-08-06 23:35:36,916 [INFO] src.visualization: Saved figure 'wordcloud_europe_asia' to outputs\figures\wordcloud_europe_asia.png
2026-08-06 23:35:46,565 [INFO] src.visualization: Report written to outputs\reports\executive_report.pdf

WindowsPath('outputs/reports/executive_report.pdf')

In [10]:
print("Pipeline completado.")

Pipeline completado.